services:
  database:
    image: mysql:9.2
    environment:
      MYSQL_DATABASE: final
      MYSQL_USER: datascientist_final_user
      MYSQL_PASSWORD: final
      MYSQL_ROOT_PASSWORD: r00t
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - '13406:3306'
  database_sqlalchemy:
    image: mysql:9.2
    environment:
      MYSQL_DATABASE: final
      MYSQL_USER: datascientist_final_user
      MYSQL_PASSWORD: final
      MYSQL_ROOT_PASSWORD: r00t
    volumes:
      - ./volumes/database_2:/var/lib/mysql
    ports:
      - '13407:3306'