INSERT INTO `final`.statistic_type (name, statistic_type,is_included_in_analysis)
    VALUES
        ("games.minutes", "games.minutes", 1),
        ("games.rating", "games.rating", 1),
        ("offsides", "offsides", 1),
        ("shots.total", "shots.total", 1),
        ("shots.on", "shots.on", 1),
        ("goals.total", "goals.total", 1),
        ("goals.conceded", "goals.conceded", 1),
        ("goals.assists", "goals.assists", 1),
        ("goals.saves", "goals.saves", 1),
        ("passes.total", "passes.total", 1),
        ("passes.key", "passes.key", 1),
        ("passes.accuracy", "passes.accuracy", 1),
        ("tackles.total", "tackles.total", 1),
        ("tackles.blocks", "tackles.blocks", 1),
        ("tackles.interceptions", "tackles.interceptions", 1),
        ("duels.total", "duels.total", 1),
        ("duels.won", "duels.won", 1),
        ("dribbles.attempts", "dribbles.attempts", 1),
        ("dribbles.success", "dribbles.success", 1),
        ("dribbles.past", "dribbles.past", 1),
        ("fouls.drawn", "fouls.drawn", 1),
        ("fouls.committed", 1),
        ("cards.yellow", "cards.yellow", 1),
        ("cards.red", "cards.red", 1),
        ("penalty.won", "penalty.won", 1),
        ("penalty.commited", "penalty.commited", 1),
        ("penalty.scored", "penalty.scored", 1),
        ("penalty.missed", "penalty.missed", 1),
        ("penalty.saved", "penalty.saved", 1)
;